package com.api.domain.enums;

public enum ErrorTypeEnum {
    INVALID_TRANSACTION_TYPE,
    ACCOUNT_HOLDER_ALREADY_EXISTS,
    ACCOUNT_NUMBER_ALREADY_EXISTS,
    ACCOUNT_HOLDER_NOT_FOUND,
    ACCOUNT_HOLDER_HAS_ACCOUNT,
    AGENCY_NOT_FOUND,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_IS_NOT_ACTIVE,
    UNAVAILABLE_BALANCE,
    DAILY_LIMIT_EXCEEDED,
    INTERNAL_SERVER_ERROR,

    ARGUMENT_NOT_VALID
}
